### ISSUE TITLE
Does SPACE include the measurement of actual physical spatial distance?

### ISSUE THREAD

**Issue by Antidington** [bm2-lab/SpaDo#3]
Dear author,

Thank you for developing these excellent tools.

While reading the SpaDo publication, I noticed this statement:：

```txt
For spot resolution spatial transcriptomic data, SpaDo obtained adjacent neighbors of each spot by searching within a specified radius as spot is distributed evenly. Then, SpaDo calculated the cell type proportion using the deconvolution results of these adjacent spots.
```

I am confused about the specific definition of the radius mentioned, and whether the definition of neighbors includes actual spatial distance measurements. This confusion leads to two questions in my actual analysis:

1. For high-resolution Spot level analysis, for example when a single spot can reach 25 microns, how should the radius size be determined?
2. If SpaDo doesn't consider actual spatial distance when constructing the adjacency matrix, how can we remove neighbors that are physically far apart, similar to the functionality implemented in [Cellcharter](https://arc.net/l/quote/tncblzif).

Looking forward to your response.

Best regards,
Jichen

**Comment by BinDuan** [comment]
Sorry for these confusions. Basically, for spot level spatial transcriptomics data, we use spatial index of each spot to calculate the neighbors instead of actual distance. Below are the point-to-point responses to your questions:
1. The guideline for setting the radius is to include a certain number of cells, typically around 30. Therefore, the higher the spot resolution (with each spot containing fewer cells), the larger the radius for Spado should be. When the spot resolution is very high, such as the 25-micron resolution you mentioned, each spot may only contain a few cells. In this case, the radius for Spado should be set larger, perhaps 5 or 6. Alternatively, you could treat the data as single-cell resolution and use the approach of setting the number of nearest neighboring cells instead of defining a radius. If you treat the data as single-cell resolution, you can use actual spatial distance directly.
2. For spot level data, SpaDo use spatial index instead of actual spatial distance to calculate neighbors. Spatial index (such as (1,1),(1,2), and so on) can also represent the distance between spots/cells. Specifically, when we use a radius to search for neighbors, our biological assumption is that as long as a spot is within the radius, it will interact with others within that range, even if it appears isolated. This isolation might be due to missing data. Even if it is not caused by missing data, the spots within the radius are still relatively close to each other. If you believe isolated spots should not be considered as neighbors, you can use the alternative method provided by SpaDo, which is K-nearest neighbors (KNN), instead of radius-based searching.

I hope it helps, if you have any more questions, please feel free to contact me.

**Comment by Antidington** [comment]
Thank you for your detailed explanation, your advice is very helpful! However, I might not have expressed Question 2 clearly. First, we used sequence-based ST and aggregated each spot at a 25-micron resolution, so I agree with your perspective.
```txt
Specifically, when we use a radius to search for neighbors, our biological assumption is that as long as a spot is within the radius, it will interact with others within that range, even if it appears isolated.
```
However, in my case, my sample contains void regions within the tissue. For example, as shown in the image, for the border spots (highlighted with red lines and blue circles), it’s evident that there is a physical gap between the two spots marked with blue circles. Would radius-based embedding be able to account for and exclude such cases?
<img width="346" alt="image" src="https://github.com/user-attachments/assets/4e2443dd-d406-4dd6-9436-38172d575d0e" />

**Comment by BinDuan** [comment]
If it’s evident that there is a physical gap  between spots and the gap is larger than the radius，radius-based embedding of SpaDo is not suitable. For this case, KNN-based embedding will be more suitable.

**Comment by Antidington** [comment]
Thank you for your advice!
